-- =============================================================================
-- StockTracker — Phase 1 Schema (Oracle Autonomous Database 26ai)
-- =============================================================================
-- Run this as your application schema user in ADB (SQL Worksheet / SQLcl).
-- Idempotent-ish: drops are commented out; uncomment to reset during dev.
-- =============================================================================

-- ---- Optional dev reset -----------------------------------------------------
-- DROP TABLE user_watchlists CASCADE CONSTRAINTS;
-- DROP TABLE app_users       CASCADE CONSTRAINTS;

-- =============================================================================
-- app_users : the small circle of friends who can log in
-- =============================================================================
CREATE TABLE app_users (
    user_id        NUMBER
                     GENERATED BY DEFAULT ON NULL AS IDENTITY
                     CONSTRAINT pk_app_users PRIMARY KEY,
    username       VARCHAR2(50)  NOT NULL,
    -- Store ONLY a salted password hash (e.g. bcrypt/pbkdf2). Never plaintext.
    password_hash  VARCHAR2(255) NOT NULL,
    display_name   VARCHAR2(100),
    is_active      NUMBER(1)     DEFAULT 1 NOT NULL,
    created_at     TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    -- Case-insensitive uniqueness so 'Upen' and 'upen' can't both register.
    CONSTRAINT uq_app_users_username UNIQUE (username),
    CONSTRAINT ck_app_users_active   CHECK (is_active IN (0, 1))
);

-- Fast case-insensitive login lookups.
CREATE UNIQUE INDEX ix_app_users_username_lower
    ON app_users (LOWER(username));

-- =============================================================================
-- user_watchlists : one row per (user, ticker) with sentiment + thesis
-- =============================================================================
CREATE TABLE user_watchlists (
    watchlist_id    NUMBER
                      GENERATED BY DEFAULT ON NULL AS IDENTITY
                      CONSTRAINT pk_user_watchlists PRIMARY KEY,
    user_id         NUMBER        NOT NULL,
    ticker          VARCHAR2(12)  NOT NULL,
    sentiment_flag  VARCHAR2(10)  DEFAULT 'NEUTRAL' NOT NULL,
    thesis          CLOB,
    -- Price when the ticker was added. NULLABLE — leave blank if unknown.
    added_price     NUMBER,
    created_at      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_watchlist_user
        FOREIGN KEY (user_id) REFERENCES app_users (user_id) ON DELETE CASCADE,
    -- A user can list a given ticker only once.
    CONSTRAINT uq_watchlist_user_ticker UNIQUE (user_id, ticker),
    -- Constrain sentiment to a known vocabulary.
    CONSTRAINT ck_watchlist_sentiment
        CHECK (sentiment_flag IN ('BULLISH', 'BEARISH', 'NEUTRAL')),
    -- Tickers are stored uppercase; enforce it at the DB level too.
    CONSTRAINT ck_watchlist_ticker_upper
        CHECK (ticker = UPPER(ticker))
);

-- Common access pattern: "all rows for this user".
CREATE INDEX ix_watchlists_user ON user_watchlists (user_id);
-- Cross-user lookups by symbol (e.g. "who else watches AAPL?").
CREATE INDEX ix_watchlists_ticker ON user_watchlists (ticker);

-- =============================================================================
-- Keep updated_at fresh on any change.
-- =============================================================================
CREATE OR REPLACE TRIGGER trg_watchlists_touch
    BEFORE UPDATE ON user_watchlists
    FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSTIMESTAMP;
END;
/

-- =============================================================================
-- MIGRATION for an EXISTING database (skip if you ran the CREATE above fresh).
-- If user_watchlists already exists without added_price, run just this line:
-- =============================================================================
-- ALTER TABLE user_watchlists ADD (added_price NUMBER);

-- =============================================================================
-- Seed a first user so you can log in immediately.
-- Replace the hash with the output of:  python make_hash.py 'your-password'
-- (placeholder below is a pbkdf2 hash for the password 'changeme')
-- =============================================================================
-- INSERT INTO app_users (username, password_hash, display_name)
-- VALUES ('upen', '<PASTE_HASH_HERE>', 'Upen');
-- COMMIT;
